/*
 * Action types
 */

// Tasks
export const SELECT_TASK = 'SELECT_TASK';
export const SELECT_TASK_ERROR = 'SELECT_TASK_ERROR';
export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';
export const GET_TASK = 'CREATE_TASK';
export const GET_TASK_ERROR = 'CREATE_TASK_ERROR';
export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const EDIT_TASK = 'EDIT_TASK';
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR';
export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

// Projects
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_ERROR = 'FETCH_PROJECTS_ERROR';
export const GET_PROJECT = 'CREATE_PROJECT';
export const GET_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';
